export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCESSFULL = "LOGIN_SUCESSFULL";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTRATION_START = "REGISTRATION_START";
export const REGISTRATION_SUCESSFULL = "REGISTRATION_SUCESSFULL";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";
